codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.5%  # Allow 0.5% decrease
        if_ci_failed: error

    patch:
      default:
        target: 80%  # New code should have high coverage
        threshold: 0%
        if_ci_failed: error

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "MyTreeUnitTests/**"
  - "MyTreeIntegrationTests/**"
  - "**/*Tests.swift"
  - "**/*App.swift"
