# SwiftLint Configuration for MyTree

# Paths to include/exclude
included:
  - MyTree
  - MyTreeIntegrationTests
  - MyTreeUnitTests

excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - MyTree.xcodeproj

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicitly_unwrapped_optional
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_optional_binding
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Analyzer rules (run with 'swiftlint analyze')
analyzer_rules:
  - unused_import
  - unused_declaration
  - typesafe_array_init
  - capture_variable

# Disabled rules
disabled_rules:
  - todo

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 80
  error: 200

type_body_length:
  warning: 400
  error: 800

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - x
    - y
    - i
    - id

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_print_in_production:
    name: "No print statements in production"
    regex: '(?<!\/\/)\bprint\('
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_unwrapping_in_production:
    name: "Avoid force unwrapping"
    regex: '(?<!\/\/)[^\w]!\s*(?=\.|\[|\))'
    message: "Use safe unwrapping (if let, guard let, or optional chaining)"
    severity: warning

# Reporters
reporter: "xcode"
